<?php

namespace app\entities;

use Yii;
use yii\behaviors\TimestampBehavior;
use yii\db\Expression;

/**
 * This is the model class for table "image".
 *
 * @property int $id
 * @property string $name
 * @property string $create_at
 * @property string $update_at
 * @property int $author_id
 * @property int $last_redactor_id
 *
 * @property User $author
 * @property User $lastRedactor
 */
class Image extends \yii\db\ActiveRecord
{

    const PATH='image';
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'image';
    }

    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::class,
                'createdAtAttribute' => 'create_at',
                'updatedAtAttribute' => 'update_at',
                'value' => new Expression('NOW()'),
            ],
        ];
    }

    public static function create(string $name) : Image
    {
        $image= new static();
        $image->name=$name;
        return $image;
    }

    public function beforeSave($insert)
    {
        if($insert)
            $this->author_id=Yii::$app->user->identity->id;
        else
            $this->last_redactor_id=Yii::$app->user->identity->id;
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['create_at', 'update_at'], 'safe'],
            [['author_id', 'last_redactor_id'], 'integer'],
            [['name'], 'string', 'max' => 255],
            [['author_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::class, 'targetAttribute' => ['author_id' => 'id']],
            [['last_redactor_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::class, 'targetAttribute' => ['last_redactor_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Название',
            'create_at' => 'Дата создание',
            'update_at' => 'Дата редактировани',
            'author_id' => 'Автор',
            'last_redactor_id' => 'Последний редактор',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAuthor()
    {
        return $this->hasOne(User::class, ['id' => 'author_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLastRedactor()
    {
        return $this->hasOne(User::class, ['id' => 'last_redactor_id']);
    }

    public static function getPath($folder) :string
    {
        return Yii::getAlias('@webroot').DIRECTORY_SEPARATOR.self::PATH.DIRECTORY_SEPARATOR.$folder;
    }

    public function getUrl($folder):string
    {
        return Yii::getAlias('@web').DIRECTORY_SEPARATOR.self::PATH.DIRECTORY_SEPARATOR.$folder;
    }

    public static function getClassImage(){
      return self::class;
    }
}
