<?php

namespace app\entities;

use Yii;
use yii\behaviors\TimestampBehavior;
use yii\db\Expression;
use app\modules\admin\forms\teachers\CreateForm;

/**
 * This is the model class for table "teachers".
 *
 * @property int $id
 * @property string $name
 * @property string $slug
 * @property int $sex
 * @property string $description
 * @property string $create_at
 * @property string $update_at
 * @property int $status
 * @property int $image_id
 * @property int $author_id
 * @property int $last_redactor_id
 * @property string last_name
 *
 * @property User $author
 * @property Image $image
 * @property User $lastRedactor
 */
class Teachers extends \yii\db\ActiveRecord
{
    const DISMISSED=0;
    const ACTIVE=1;

    const MEN = 0;
    const WOMEN=1;

    const FOLDER='teacher';

    static $nameStatus=[
        self::ACTIVE    =>  'Работает',
        self::DISMISSED =>  'Уволен'
    ];

    static $nameSex=[
        self::MEN=>'Мужчина',
        self::WOMEN=>'Женщина'
    ];



    public static function create(CreateForm $form)
    {
        $teacher=new static();
        $teacher->sex=$form->sex;
        $teacher->status=$form->status;
        $teacher->name=$form->name;
        $teacher->last_name=$form->last_name;
        $teacher->description=$form->description;

    }
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'teachers';
    }

    public function behaviors()
    {
        return [
            'time'=>[
                'class' => TimestampBehavior::class,
                'createdAtAttribute' => 'create_at',
                'updatedAtAttribute' => 'update_at',
                'value' => new Expression('NOW()'),
            ],
             'slug' => [
                 'class' => 'Zelenin\yii\behaviors\Slug',
                 'slugAttribute' => 'slug',
                 'attribute' => 'name',
                 'ensureUnique' => true,
                 'replacement' => '-',
                 'lowercase' => true,
                 'immutable' => false,

             ]

        ];
    }

    public function beforeSave($insert)
    {
        if($insert)
            $this->author_id=Yii::$app->user->identity->id;
        else
            $this->last_redactor_id=Yii::$app->user->identity->id;
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['sex', 'status', 'image_id', 'author_id', 'last_redactor_id'], 'integer'],
            [['description'], 'string'],
            [['create_at', 'update_at'], 'safe'],
            [['name', 'slug','last_name'], 'string', 'max' => 255],
            [['author_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::class, 'targetAttribute' => ['author_id' => 'id']],
            [['image_id'], 'exist', 'skipOnError' => true, 'targetClass' => Image::class, 'targetAttribute' => ['image_id' => 'id']],
            [['last_redactor_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::class, 'targetAttribute' => ['last_redactor_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Имя ',
            'last_name'=>'Фамилия',
            'slug' => 'Ярлык',
            'sex' => 'Пол',
            'description' => 'Описание',
            'create_at' => 'Дата создания',
            'update_at' => 'Дата редактирования',
            'status' => 'Статус',
            'image_id' => 'Картинка',
            'author_id' => 'Автор',
            'last_redactor_id' => 'Последний редактор',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAuthor()
    {
        return $this->hasOne(User::class, ['id' => 'author_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getImage()
    {
        return $this->hasOne(Image::class, ['id' => 'image_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLastRedactor()
    {
        return $this->hasOne(User::class, ['id' => 'last_redactor_id']);
    }

    public function getNameStatus()
    {
        return self::$nameStatus[$this->status];
    }

    public function getNameSex(){
        return self::$nameSex[$this->sex];
    }
}
